[package]
name = "palindrome"
version = "0.1.0"
edition = "2024"

[dependencies]
palindrome-string-utils = { path = "../palindrome-string-utils" }
palindrome-user-input = { path = "../palindrome-user-input" }
